import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/MainHeader";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col  min-h-screen bg-purple-500 relative`}
            >
                <div className="relative -z-10 bg-emerald-500  w-full h-full">
                    <div className="h-128 w-128 bg-amber-300/80 absolute blur-3xl top-40 left-50 mix-blend-multiply rounded-full"></div>
                    <div className="h-128 w-128 bg-sky-300/80 absolute blur-3xl right-100 top-70 -rotate-12 mix-blend-multiply rounded-full"></div>
                    <div className="h-128 w-128 bg-emerald-300/80 absolute blur-3xl right-50 top-40 mix-blend-multiply -top-50 rounded-full"></div>
                </div>
                <MainHeader />
                <main className="">{children}</main>

                <Footer />
            </body>
        </html>
    );
}
